package datamanagement;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.JFrame;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;

import java.awt.Font;

import static javax.swing.BorderFactory.createTitledBorder;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class CheckGradeUserInterface extends JFrame
        implements IUnitLister, IStudentLister
{
  // ===========================================================================
  // Variables
  // ===========================================================================
  
  
  
  private CheckGradeController controller_;
  private DefaultComboBoxModel unitComboBoxModel_;    // Parameterize model to <String>?
  private DefaultComboBoxModel studentComboBoxModel_;
  
  private float assessmentOneMark_;
  private float assessmentTwoMark_;
  private float examMark_;
  
  private Integer studentId_;


  
  // ===========================================================================
  // Constructors
  // ===========================================================================
  
  
  
  public CheckGradeUserInterface(CheckGradeController ctl)
  {
    this.controller_ = ctl;
    unitComboBoxModel_ = new DefaultComboBoxModel(new String[0]);
    studentComboBoxModel_ = new DefaultComboBoxModel(new String[0]);
    initComponents();
    selectUnitComboBox.setModel(unitComboBoxModel_);
    selectStudentComboBox.setModel(studentComboBoxModel_);
    errorMessageLabel.setText("");
  }


  
  // ===========================================================================
  // Methods
  // ===========================================================================
  
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed"
  // desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    checkGradeTitleLabel = new JLabel();
    unitSelectionPanel = new JPanel();
    selectUnitComboBox = new JComboBox();
    studentSelectionPanel = new JPanel();
    selectStudentComboBox = new JComboBox();
    markDisplayPanel = new JPanel();
    assessmentOneLabel = new JLabel();
    assessmentTwoLabel = new JLabel();
    examLabel = new JLabel();
    assessementOneMarkTextField = new JTextField();
    assessmentTwoMarkTestField = new JTextField();
    examMarkTextField = new JTextField();
    changeButton = new JButton();
    gradeDisplayPanel = new JPanel();
    gradeDisplayLabel = new JLabel();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    checkGradeTitleLabel.setFont(new Font("Tahoma", 0, 16)); // NOI18N
    checkGradeTitleLabel.setText("Check Grade UI");

    unitSelectionPanel
            .setBorder(BorderFactory.createTitledBorder("Unit"));

    selectUnitComboBox.setModel(unitComboBoxModel_);
    selectUnitComboBox.addItemListener(new ItemListener()
    {
      public void itemStateChanged(ItemEvent evt)
      {
        jComboBox1ItemStateChanged(evt);
      }
    });

    GroupLayout gl_unitSelectionPanel = new GroupLayout(
            unitSelectionPanel);
    unitSelectionPanel.setLayout(gl_unitSelectionPanel);
    gl_unitSelectionPanel.setHorizontalGroup(gl_unitSelectionPanel
            .createParallelGroup(Alignment.LEADING)
            .addGroup(gl_unitSelectionPanel.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(selectUnitComboBox,
                            GroupLayout.PREFERRED_SIZE, 185,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));
    gl_unitSelectionPanel.setVerticalGroup(gl_unitSelectionPanel
            .createParallelGroup(Alignment.LEADING)
            .addGroup(gl_unitSelectionPanel.createSequentialGroup()
                    .addComponent(selectUnitComboBox,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));

    studentSelectionPanel
            .setBorder(createTitledBorder("Student"));

    selectStudentComboBox.setModel(studentComboBoxModel_);
    selectStudentComboBox.addItemListener(new ItemListener()
    {
      public void itemStateChanged(ItemEvent evt)
      {
        jComboBox2ItemStateChanged(evt);
      }
    });

    GroupLayout gl_studentSelectionPanel = new GroupLayout(
            studentSelectionPanel);
    studentSelectionPanel.setLayout(gl_studentSelectionPanel);
    gl_studentSelectionPanel.setHorizontalGroup(gl_studentSelectionPanel
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_studentSelectionPanel.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(selectStudentComboBox,
                            GroupLayout.PREFERRED_SIZE, 185,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));
    gl_studentSelectionPanel.setVerticalGroup(gl_studentSelectionPanel
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_studentSelectionPanel.createSequentialGroup()
                    .addComponent(selectStudentComboBox,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));

    markDisplayPanel
            .setBorder(createTitledBorder("Marks"));

    assessmentOneLabel.setText("Asg1:");

    assessmentTwoLabel.setText("Asg2:");

    examLabel.setText("Exam:");

    assessementOneMarkTextField.setEditable(false);
    assessementOneMarkTextField.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    assessmentTwoMarkTestField.setEditable(false);
    assessmentTwoMarkTestField.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    examMarkTextField.setEditable(false);
    examMarkTextField.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    changeButton.setText("Change");
    changeButton.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    checkGradeButton = new JButton();

    checkGradeButton.setText("Check Grade");
    checkGradeButton.setActionCommand("checkGrade");
    checkGradeButton.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton3ActionPerformed(evt);
      }
    });

    GroupLayout gl_markDisplayPanel = new GroupLayout(
            markDisplayPanel);
    gl_markDisplayPanel.setHorizontalGroup(gl_markDisplayPanel
            .createParallelGroup(Alignment.LEADING)
            .addGroup(gl_markDisplayPanel.createSequentialGroup()
                    .addGroup(gl_markDisplayPanel
                            .createParallelGroup(Alignment.LEADING)
                            .addGroup(gl_markDisplayPanel
                                    .createSequentialGroup().addContainerGap()
                                    .addComponent(assessmentOneLabel)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(assessementOneMarkTextField,
                                            GroupLayout.PREFERRED_SIZE, 59,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(assessmentTwoLabel))
                            .addGroup(gl_markDisplayPanel
                                    .createSequentialGroup().addGap(85)
                                    .addComponent(changeButton,
                                            GroupLayout.PREFERRED_SIZE, 84,
                                            GroupLayout.PREFERRED_SIZE)))
                    .addGap(18)
                    .addGroup(gl_markDisplayPanel
                            .createParallelGroup(Alignment.TRAILING)
                            .addGroup(gl_markDisplayPanel
                                    .createSequentialGroup()
                                    .addComponent(assessmentTwoMarkTestField,
                                            GroupLayout.PREFERRED_SIZE, 59,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addGap(18).addComponent(examLabel))
                            .addComponent(checkGradeButton))
                    .addGap(18)
                    .addComponent(examMarkTextField, GroupLayout.PREFERRED_SIZE,
                            59, GroupLayout.PREFERRED_SIZE)
                    .addGap(15)));
    gl_markDisplayPanel.setVerticalGroup(
            gl_markDisplayPanel.createParallelGroup(Alignment.LEADING)
                    .addGroup(gl_markDisplayPanel.createSequentialGroup()
                            .addGroup(gl_markDisplayPanel
                                    .createParallelGroup(Alignment.BASELINE)
                                    .addComponent(assessmentOneLabel)
                                    .addComponent(assessementOneMarkTextField,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                            .addComponent(assessmentTwoLabel)
                            .addComponent(assessmentTwoMarkTestField,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE)
                            .addComponent(examLabel)
                            .addComponent(examMarkTextField,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.UNRELATED)
                    .addGroup(gl_markDisplayPanel
                            .createParallelGroup(Alignment.BASELINE)
                            .addComponent(changeButton)
                            .addComponent(checkGradeButton))
                    .addContainerGap()));
    markDisplayPanel.setLayout(gl_markDisplayPanel);

    gradeDisplayPanel
            .setBorder(createTitledBorder("Grade"));

    gradeDisplayLabel.setFont(new Font("Tahoma", 0, 24)); // NOI18N
    gradeDisplayLabel.setForeground(new Color(255, 0, 0));
    gradeDisplayLabel.setHorizontalAlignment(SwingConstants.CENTER);
    gradeDisplayLabel.setText("grade");

    GroupLayout gl_gradeDisplayPanel = new GroupLayout(
            gradeDisplayPanel);
    gradeDisplayPanel.setLayout(gl_gradeDisplayPanel);
    gl_gradeDisplayPanel.setHorizontalGroup(gl_gradeDisplayPanel
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(gradeDisplayLabel,
                    GroupLayout.Alignment.TRAILING,
                    GroupLayout.DEFAULT_SIZE, 153,
                    Short.MAX_VALUE));
    gl_gradeDisplayPanel.setVerticalGroup(gl_gradeDisplayPanel
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_gradeDisplayPanel.createSequentialGroup()
                    .addGap(34, 34, 34).addComponent(gradeDisplayLabel)
                    .addContainerGap(43, Short.MAX_VALUE)));

    errorMessageLabel = new JLabel();
    errorMessageLabel.setText("Error message");
    errorMessageLabel.setForeground(Color.RED);
    errorMessageLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
    saveButton = new JButton();

    saveButton.setText("Save");
    saveButton.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });

    GroupLayout layout = new GroupLayout(
            getContentPane());
    layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGroup(layout
                    .createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup().addContainerGap()
                            .addComponent(errorMessageLabel,
                                    GroupLayout.DEFAULT_SIZE, 400,
                                    Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup().addContainerGap()
                            .addGroup(layout
                                    .createParallelGroup(Alignment.LEADING,
                                            false)
                                    .addComponent(markDisplayPanel,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout
                                                    .createParallelGroup(
                                                            Alignment.LEADING)
                                                    .addComponent(
                                                            unitSelectionPanel,
                                                            GroupLayout.PREFERRED_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                            studentSelectionPanel,
                                                            GroupLayout.PREFERRED_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.PREFERRED_SIZE))
                                            .addGap(18)
                                            .addComponent(gradeDisplayPanel,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    GroupLayout.DEFAULT_SIZE,
                                                    GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup().addGap(157)
                            .addComponent(checkGradeTitleLabel))
                    .addGroup(layout.createSequentialGroup().addGap(165)
                            .addComponent(saveButton,
                                    GroupLayout.PREFERRED_SIZE, 86,
                                    GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addContainerGap()
                    .addComponent(checkGradeTitleLabel).addGap(13)
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(unitSelectionPanel,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(studentSelectionPanel,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                            .addComponent(gradeDisplayPanel,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markDisplayPanel, GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(saveButton).addGap(11)
                    .addComponent(errorMessageLabel, GroupLayout.PREFERRED_SIZE,
                            30, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    getContentPane().setLayout(layout);

    pack();
  }// </editor-fold>//GEN-END:initComponents



  private void jComboBox1ItemStateChanged(ItemEvent evt)
  {// GEN-FIRST:event_jComboBox1ItemStateChanged
    String cU = (String) selectUnitComboBox.getSelectedItem();
    Refresh3();
    clearStudents();
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      if (cU.equals((String) selectUnitComboBox.getItemAt(0))) {
        cU = "NONE";
      }
      controller_.unitSelected(cU);
    }
  }// GEN-LAST:event_jComboBox1ItemStateChanged



  private void jComboBox2ItemStateChanged(ItemEvent evt)
  {// GEN-FIRST:event_jComboBox2ItemStateChanged
    Refresh3();
    String cS = (String) selectStudentComboBox.getSelectedItem();
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      if (cS.equals((String) selectStudentComboBox.getItemAt(0))) {
        studentId_ = new Integer(0);
        controller_.studentSelected(studentId_);
      }
      else {
        studentId_ = new Integer(cS.split("\\s")[0]);
      }
      controller_.studentSelected(studentId_);
    }
  }// GEN-LAST:event_jComboBox2ItemStateChanged



  private void jButton3ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton3ActionPerformed
    assessmentOneMark_ = new Float(assessementOneMarkTextField.getText()).floatValue();
    assessmentTwoMark_ = new Float(assessmentTwoMarkTestField.getText()).floatValue();
    examMark_ = new Float(examMarkTextField.getText()).floatValue();
    // lblErrMsg.setText("");
    try {
      String s = controller_.checkGrade(assessmentOneMark_, assessmentTwoMark_, examMark_);
      gradeDisplayLabel.setText(s);
    }
    catch (RuntimeException re) {
      errorMessageLabel.setText(re.getMessage());
    }
  }// GEN-LAST:event_jButton3ActionPerformed



  private void jButton1ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton1ActionPerformed
    controller_.enableChangeMarks();
    gradeDisplayLabel.setText("");
    // lblErrMsg.setText("");
  }// GEN-LAST:event_jButton1ActionPerformed



  private void jTextFieldKeyTyped(KeyEvent evt)
  {// GEN-FIRST:event_jTextField1KeyTyped
    gradeDisplayLabel.setText("");
    errorMessageLabel.setText("");
  }// GEN-LAST:event_jTextField1KeyTyped



  private void jButton2ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton2ActionPerformed
    float asg1 = new Float(assessementOneMarkTextField.getText()).floatValue();
    float asg2 = new Float(assessmentTwoMarkTestField.getText()).floatValue();
    float exam = new Float(examMarkTextField.getText()).floatValue();
    errorMessageLabel.setText("");
    try {
      controller_.saveGrade(asg1, asg2, exam);
      // jButton3ActionPerformed(null);
    }
    catch (RuntimeException re) {
      errorMessageLabel.setText(re.getMessage());
    }
  }// GEN-LAST:event_jButton2ActionPerformed



  public void clearUnits()
  {
    unitComboBoxModel_.removeAllElements();
    unitComboBoxModel_.addElement("<none selected>");
    clearStudents();
  }



  public void addUnit(IUnit u)
  {
    unitComboBoxModel_.addElement(u.getUnitCode());
  }



  public void setState1(boolean b)
  {
    selectUnitComboBox.setEnabled(b);
    errorMessageLabel.setText("");
  }



  public void clearStudents()
  {
    studentComboBoxModel_.removeAllElements();
    studentComboBoxModel_.addElement("<none selected>");
  }



  public void addStudent(IStudent student)
  {
    studentComboBoxModel_.addElement(student.getID().toString() + " : " + student.getFirstName()
            + " " + student.getLastName());
  }



  public void setState2(boolean b)
  {
    selectStudentComboBox.setEnabled(b);
    errorMessageLabel.setText("");
  }



  public void setRecord(IStudentUnitRecord record)
  {
    assessementOneMarkTextField.setText(new Float(record.getAssessmentOneMark()).toString());
    assessmentTwoMarkTestField.setText(new Float(record.getAssessmentTwoMark()).toString());
    examMarkTextField.setText(new Float(record.getExamMark()).toString());
    gradeDisplayLabel.setText("");
  }



  public void Refresh3()
  {
    assessementOneMarkTextField.setText("");
    assessmentTwoMarkTestField.setText("");
    examMarkTextField.setText("");
    gradeDisplayLabel.setText("");
    errorMessageLabel.setText("");
    assessementOneMarkTextField.setEditable(false);
    assessmentTwoMarkTestField.setEditable(false);
    examMarkTextField.setEditable(false);
  }



  public void setState3(boolean b)
  {
    checkGradeButton.setEnabled(b);
  }



  public void setState4(boolean b)
  {
    changeButton.setEnabled(b);
    // gradeLB.setText("");
  }



  public void setState5(boolean b)
  {
    assessementOneMarkTextField.setEditable(b);
    assessmentTwoMarkTestField.setEditable(b);
    examMarkTextField.setEditable(b);
  }



  public void setState6(boolean b)
  {
    saveButton.setEnabled(b);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton changeButton;
  private JButton checkGradeButton;
  private JButton saveButton;
  private JComboBox selectUnitComboBox;
  private JComboBox selectStudentComboBox;
  private JLabel checkGradeTitleLabel;
  private JLabel assessmentOneLabel;
  private JLabel assessmentTwoLabel;
  private JLabel examLabel;
  private JLabel gradeDisplayLabel;
  private JLabel errorMessageLabel;
  private JPanel unitSelectionPanel;
  private JPanel studentSelectionPanel;
  private JPanel markDisplayPanel;
  private JPanel gradeDisplayPanel;
  private JTextField assessementOneMarkTextField;
  private JTextField assessmentTwoMarkTestField;
  private JTextField examMarkTextField;
}
