package datamanagement;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.JFrame;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;

import java.awt.Font;
import java.awt.Color;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class CheckGradeUserInterface extends JFrame
        implements IUnitLister, IStudentLister
{
  // ===========================================================================
  // Variables
  // ===========================================================================



  private CheckGradeController controller_;
  private DefaultComboBoxModel unitComboBoxModel_;    // Parameterize model to
  private DefaultComboBoxModel studentComboBoxModel_; // <String>?
  
  private float assessmentOneMark_;
  private float assessmentTwoMark_;
  private float examMark_;

  private Integer studentId_;



  // ===========================================================================
  // Constructors
  // ===========================================================================



  public CheckGradeUserInterface(CheckGradeController controller)
  {
    this.controller_ = controller;
    unitComboBoxModel_ = new DefaultComboBoxModel(new String[0]);
    studentComboBoxModel_ = new DefaultComboBoxModel(new String[0]);
    
    initComponents();
    
    selectUnitComboBox_.setModel(unitComboBoxModel_);
    selectStudentComboBox_.setModel(studentComboBoxModel_);
    errorMessageLabel_.setText("");
  }



  // ===========================================================================
  // Methods
  // ===========================================================================



  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed"
  // desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    checkGradeTitleLabel_ = new JLabel();
    unitSelectionPanel_ = new JPanel();
    selectUnitComboBox_ = new JComboBox();
    studentSelectionPanel_ = new JPanel();
    selectStudentComboBox_ = new JComboBox();
    markDisplayPanel_ = new JPanel();
    assessmentOneLabel_ = new JLabel();
    assessmentTwoLabel_ = new JLabel();
    examLabel_ = new JLabel();
    assessementOneMarkTextField_ = new JTextField();
    assessmentTwoMarkTextField_ = new JTextField();
    examMarkTextField_ = new JTextField();
    changeButton_ = new JButton();
    gradeDisplayPanel_ = new JPanel();
    gradeDisplayLabel_ = new JLabel();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    checkGradeTitleLabel_.setFont(new Font("Tahoma", 0, 16)); // NOI18N
    checkGradeTitleLabel_.setText("Check Grade UI");

    unitSelectionPanel_.setBorder(BorderFactory.createTitledBorder("Unit"));

    selectUnitComboBox_.setModel(unitComboBoxModel_);
    selectUnitComboBox_.addItemListener(new ItemListener()
    {
      public void itemStateChanged(ItemEvent evt)
      {
        jComboBox1ItemStateChanged(evt);
      }
    });

    GroupLayout gl_unitSelectionPanel_ = new GroupLayout(unitSelectionPanel_);
    unitSelectionPanel_.setLayout(gl_unitSelectionPanel_);
    gl_unitSelectionPanel_.setHorizontalGroup(
            gl_unitSelectionPanel_.createParallelGroup(Alignment.LEADING)
                    .addGroup(gl_unitSelectionPanel_.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(selectUnitComboBox_,
                                    GroupLayout.PREFERRED_SIZE, 185,
                                    GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)));
    gl_unitSelectionPanel_.setVerticalGroup(
            gl_unitSelectionPanel_.createParallelGroup(Alignment.LEADING)
                    .addGroup(gl_unitSelectionPanel_.createSequentialGroup()
                            .addComponent(selectUnitComboBox_,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE)));

    studentSelectionPanel_.setBorder(BorderFactory.createTitledBorder("Student"));

    selectStudentComboBox_.setModel(studentComboBoxModel_);
    selectStudentComboBox_.addItemListener(new ItemListener()
    {
      public void itemStateChanged(ItemEvent evt)
      {
        jComboBox2ItemStateChanged(evt);
      }
    });

    GroupLayout gl_studentSelectionPanel_ = new GroupLayout(
            studentSelectionPanel_);
    studentSelectionPanel_.setLayout(gl_studentSelectionPanel_);
    gl_studentSelectionPanel_.setHorizontalGroup(gl_studentSelectionPanel_
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_studentSelectionPanel_.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(selectStudentComboBox_,
                            GroupLayout.PREFERRED_SIZE, 185,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));
    gl_studentSelectionPanel_.setVerticalGroup(gl_studentSelectionPanel_
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_studentSelectionPanel_.createSequentialGroup()
                    .addComponent(selectStudentComboBox_,
                            GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE,
                            Short.MAX_VALUE)));

    markDisplayPanel_.setBorder(BorderFactory.createTitledBorder("Marks"));

    assessmentOneLabel_.setText("Asg1:");

    assessmentTwoLabel_.setText("Asg2:");

    examLabel_.setText("Exam:");

    assessementOneMarkTextField_.setEditable(false);
    assessementOneMarkTextField_.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    assessmentTwoMarkTextField_.setEditable(false);
    assessmentTwoMarkTextField_.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    examMarkTextField_.setEditable(false);
    examMarkTextField_.addKeyListener(new KeyAdapter()
    {
      public void keyTyped(KeyEvent evt)
      {
        jTextFieldKeyTyped(evt);
      }
    });

    changeButton_.setText("Change");
    changeButton_.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    checkGradeButton_ = new JButton();

    checkGradeButton_.setText("Check Grade");
    checkGradeButton_.setActionCommand("checkGrade");
    checkGradeButton_.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton3ActionPerformed(evt);
      }
    });

    GroupLayout gl_markDisplayPanel_ = new GroupLayout(markDisplayPanel_);
    gl_markDisplayPanel_.setHorizontalGroup(gl_markDisplayPanel_
            .createParallelGroup(Alignment.LEADING)
            .addGroup(gl_markDisplayPanel_.createSequentialGroup()
                    .addGroup(gl_markDisplayPanel_
                            .createParallelGroup(Alignment.LEADING)
                            .addGroup(gl_markDisplayPanel_
                                    .createSequentialGroup().addContainerGap()
                                    .addComponent(assessmentOneLabel_)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(assessementOneMarkTextField_,
                                            GroupLayout.PREFERRED_SIZE, 59,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addGap(18)
                                    .addComponent(assessmentTwoLabel_))
                            .addGroup(gl_markDisplayPanel_
                                    .createSequentialGroup().addGap(85)
                                    .addComponent(changeButton_,
                                            GroupLayout.PREFERRED_SIZE, 84,
                                            GroupLayout.PREFERRED_SIZE)))
                    .addGap(18)
                    .addGroup(gl_markDisplayPanel_
                            .createParallelGroup(Alignment.TRAILING)
                            .addGroup(gl_markDisplayPanel_
                                    .createSequentialGroup()
                                    .addComponent(assessmentTwoMarkTextField_,
                                            GroupLayout.PREFERRED_SIZE, 59,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addGap(18).addComponent(examLabel_))
                            .addComponent(checkGradeButton_))
                    .addGap(18)
                    .addComponent(examMarkTextField_, GroupLayout.PREFERRED_SIZE,
                            59, GroupLayout.PREFERRED_SIZE)
                    .addGap(15)));
    gl_markDisplayPanel_.setVerticalGroup(
            gl_markDisplayPanel_.createParallelGroup(Alignment.LEADING)
                    .addGroup(gl_markDisplayPanel_.createSequentialGroup()
                            .addGroup(gl_markDisplayPanel_
                                    .createParallelGroup(Alignment.BASELINE)
                                    .addComponent(assessmentOneLabel_)
                                    .addComponent(assessementOneMarkTextField_,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                            .addComponent(assessmentTwoLabel_)
                            .addComponent(assessmentTwoMarkTextField_,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE)
                            .addComponent(examLabel_)
                            .addComponent(examMarkTextField_,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.UNRELATED)
                    .addGroup(gl_markDisplayPanel_
                            .createParallelGroup(Alignment.BASELINE)
                            .addComponent(changeButton_)
                            .addComponent(checkGradeButton_))
                    .addContainerGap()));
    markDisplayPanel_.setLayout(gl_markDisplayPanel_);

    gradeDisplayPanel_.setBorder(BorderFactory.createTitledBorder("Grade"));

    gradeDisplayLabel_.setFont(new Font("Tahoma", 0, 24)); // NOI18N
    gradeDisplayLabel_.setForeground(new Color(255, 0, 0));
    gradeDisplayLabel_.setHorizontalAlignment(SwingConstants.CENTER);
    gradeDisplayLabel_.setText("grade");

    GroupLayout gl_gradeDisplayPanel_ = new GroupLayout(gradeDisplayPanel_);
    gradeDisplayPanel_.setLayout(gl_gradeDisplayPanel_);
    gl_gradeDisplayPanel_.setHorizontalGroup(gl_gradeDisplayPanel_
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(gradeDisplayLabel_, GroupLayout.Alignment.TRAILING,
                    GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE));
    gl_gradeDisplayPanel_.setVerticalGroup(gl_gradeDisplayPanel_
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(gl_gradeDisplayPanel_.createSequentialGroup()
                    .addGap(34, 34, 34).addComponent(gradeDisplayLabel_)
                    .addContainerGap(43, Short.MAX_VALUE)));

    errorMessageLabel_ = new JLabel();
    errorMessageLabel_.setText("Error message");
    errorMessageLabel_.setForeground(Color.RED);
    errorMessageLabel_.setFont(new Font("Tahoma", Font.PLAIN, 12));
    saveButton_ = new JButton();

    saveButton_.setText("Save");
    saveButton_.addActionListener(new ActionListener()
    {
      public void actionPerformed(ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });

    GroupLayout layout = new GroupLayout(getContentPane());
    layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addGroup(layout
                    .createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup().addContainerGap()
                            .addComponent(errorMessageLabel_,
                                    GroupLayout.DEFAULT_SIZE, 400,
                                    Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup().addContainerGap()
                            .addGroup(layout
                                    .createParallelGroup(Alignment.LEADING,
                                            false)
                                    .addComponent(markDisplayPanel_,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout
                                                    .createParallelGroup(
                                                            Alignment.LEADING)
                                                    .addComponent(
                                                            unitSelectionPanel_,
                                                            GroupLayout.PREFERRED_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(
                                                            studentSelectionPanel_,
                                                            GroupLayout.PREFERRED_SIZE,
                                                            GroupLayout.DEFAULT_SIZE,
                                                            GroupLayout.PREFERRED_SIZE))
                                            .addGap(18)
                                            .addComponent(gradeDisplayPanel_,
                                                    GroupLayout.PREFERRED_SIZE,
                                                    GroupLayout.DEFAULT_SIZE,
                                                    GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup().addGap(157)
                            .addComponent(checkGradeTitleLabel_))
                    .addGroup(layout.createSequentialGroup().addGap(165)
                            .addComponent(saveButton_,
                                    GroupLayout.PREFERRED_SIZE, 86,
                                    GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup().addContainerGap()
                    .addComponent(checkGradeTitleLabel_).addGap(13)
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(unitSelectionPanel_,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(studentSelectionPanel_,
                                            GroupLayout.PREFERRED_SIZE,
                                            GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                            .addComponent(gradeDisplayPanel_,
                                    GroupLayout.PREFERRED_SIZE,
                                    GroupLayout.DEFAULT_SIZE,
                                    GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED,
                            GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markDisplayPanel_, GroupLayout.PREFERRED_SIZE,
                            GroupLayout.DEFAULT_SIZE,
                            GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(saveButton_).addGap(11)
                    .addComponent(errorMessageLabel_, GroupLayout.PREFERRED_SIZE,
                            30, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()));
    getContentPane().setLayout(layout);

    pack();
  }// </editor-fold>//GEN-END:initComponents



  private void jComboBox1ItemStateChanged(ItemEvent evt)
  {// GEN-FIRST:event_jComboBox1ItemStateChanged
    String cU = (String) selectUnitComboBox_.getSelectedItem();
    clearDisplayedText();
    clearStudents();
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      if (cU.equals((String) selectUnitComboBox_.getItemAt(0))) {
        cU = "NONE";
      }
      controller_.unitSelected(cU);
    }
  }// GEN-LAST:event_jComboBox1ItemStateChanged



  private void jComboBox2ItemStateChanged(ItemEvent evt)
  {// GEN-FIRST:event_jComboBox2ItemStateChanged
    clearDisplayedText();
    String cS = (String) selectStudentComboBox_.getSelectedItem();
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      if (cS.equals((String) selectStudentComboBox_.getItemAt(0))) {
        studentId_ = new Integer(0);
        controller_.studentSelected(studentId_);
      }
      else {
        studentId_ = new Integer(cS.split("\\s")[0]);
      }
      controller_.studentSelected(studentId_);
    }
  }// GEN-LAST:event_jComboBox2ItemStateChanged



  private void jButton3ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton3ActionPerformed
    assessmentOneMark_ = new Float(assessementOneMarkTextField_.getText())
            .floatValue();
    assessmentTwoMark_ = new Float(assessmentTwoMarkTextField_.getText())
            .floatValue();
    examMark_ = new Float(examMarkTextField_.getText()).floatValue();
    // lblErrMsg.setText("");
    try {
      String s = controller_.checkGrade(assessmentOneMark_, assessmentTwoMark_,
              examMark_);
      gradeDisplayLabel_.setText(s);
    }
    catch (RuntimeException re) {
      errorMessageLabel_.setText(re.getMessage());
    }
  }// GEN-LAST:event_jButton3ActionPerformed



  private void jButton1ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton1ActionPerformed
    controller_.enableChangeMarks();
    gradeDisplayLabel_.setText("");
    // lblErrMsg.setText("");
  }// GEN-LAST:event_jButton1ActionPerformed



  private void jTextFieldKeyTyped(KeyEvent evt)
  {// GEN-FIRST:event_jTextField1KeyTyped
    gradeDisplayLabel_.setText("");
    errorMessageLabel_.setText("");
  }// GEN-LAST:event_jTextField1KeyTyped



  private void jButton2ActionPerformed(ActionEvent evt)
  {// GEN-FIRST:event_jButton2ActionPerformed
    float asg1 = new Float(assessementOneMarkTextField_.getText()).floatValue();
    float asg2 = new Float(assessmentTwoMarkTextField_.getText()).floatValue();
    float exam = new Float(examMarkTextField_.getText()).floatValue();
    errorMessageLabel_.setText("");
    try {
      controller_.saveGrade(asg1, asg2, exam);
      // jButton3ActionPerformed(null);
    }
    catch (RuntimeException re) {
      errorMessageLabel_.setText(re.getMessage());
    }
  }// GEN-LAST:event_jButton2ActionPerformed



  public void clearUnits()
  {
    unitComboBoxModel_.removeAllElements();
    unitComboBoxModel_.addElement("<none selected>");
    clearStudents();
  }



  public void clearStudents()
  {
    studentComboBoxModel_.removeAllElements();
    studentComboBoxModel_.addElement("<none selected>");
  }



  public void addUnit(IUnit unit)
  {
    unitComboBoxModel_.addElement(unit.getUnitCode());
  }



  public void addStudent(IStudent student)
  {
    studentComboBoxModel_.addElement(student.getID().toString() + " : "
            + student.getFirstName() + " " + student.getLastName());
  }



  public void setRecord(IStudentUnitRecord record)
  {
    assessementOneMarkTextField_
            .setText(new Float(record.getAssessmentOneMark()).toString());
    assessmentTwoMarkTextField_
            .setText(new Float(record.getAssessmentTwoMark()).toString());
    examMarkTextField_.setText(new Float(record.getExamMark()).toString());
    gradeDisplayLabel_.setText("");
  }



  public void clearDisplayedText()
  {
    assessementOneMarkTextField_.setText("");
    assessmentTwoMarkTextField_.setText("");
    examMarkTextField_.setText("");
    gradeDisplayLabel_.setText("");
    errorMessageLabel_.setText("");
    
    assessementOneMarkTextField_.setEditable(false);
    assessmentTwoMarkTextField_.setEditable(false);
    examMarkTextField_.setEditable(false);
  }



  public void setSelectUnitComboBoxEnabled(boolean shouldEnable)
  {
    selectUnitComboBox_.setEnabled(shouldEnable);
    errorMessageLabel_.setText("");
  }



  public void setCheckGradeButtonEnabled(boolean shouldEnable)
  {
    checkGradeButton_.setEnabled(shouldEnable);
  }



  public void setSelectStudentComboBoxEnabled(boolean shouldEnable)
  {
    selectStudentComboBox_.setEnabled(shouldEnable);
    errorMessageLabel_.setText("");
  }



  public void setChangeButtonEnabled(boolean shouldEnable)
  {
    changeButton_.setEnabled(shouldEnable);
    // gradeLB.setText("");
  }



  public void setMarkEntryTextFieldsEnabled(boolean shouldEnable)
  {
    assessementOneMarkTextField_.setEditable(shouldEnable);
    assessmentTwoMarkTextField_.setEditable(shouldEnable);
    examMarkTextField_.setEditable(shouldEnable);
  }



  public void setSaveButtonEnabled(boolean shouldEnable)
  {
    saveButton_.setEnabled(shouldEnable);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton changeButton_;
  private JButton checkGradeButton_;
  private JButton saveButton_;
  private JComboBox selectUnitComboBox_;
  private JComboBox selectStudentComboBox_;
  private JLabel checkGradeTitleLabel_;
  private JLabel assessmentOneLabel_;
  private JLabel assessmentTwoLabel_;
  private JLabel examLabel_;
  private JLabel gradeDisplayLabel_;
  private JLabel errorMessageLabel_;
  private JPanel unitSelectionPanel_;
  private JPanel studentSelectionPanel_;
  private JPanel markDisplayPanel_;
  private JPanel gradeDisplayPanel_;
  private JTextField assessementOneMarkTextField_;
  private JTextField assessmentTwoMarkTextField_;
  private JTextField examMarkTextField_;
}
